language: c

env:
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install busted

before_script:
  - luarocks --local make PCRE_LIBDIR=/usr/lib/x86_64-linux-gnu

script: "busted tests/device_detect_test.lua"

notifications:
  recipients:
    - boby@frozenminds.com
  email:
    on_success: change
    on_failure: always
